apiVersion: v1
kind: Template
metadata:
  name: fabric8-tenant-che-migration-endpoints-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      provider: fabric8
      project: fabric8-tenant-che-migration-endpoints
      version: latest
      group: quickstart
    name: fabric8-tenant-che-migration-endpoints
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: fabric8-tenant-che-migration-endpoints
      group: quickstart
    template:
      metadata:
        labels:
          provider: fabric8
          project: fabric8-tenant-che-migration-endpoints
          version: ${VERSION}
          group: quickstart
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: ${IMAGE}
          imagePullPolicy: Always
          command: [ "./startRestEndpointsLocally.sh" ]
          name: fabric8-tenant-che-migration-endpoints
          ports:
          - containerPort: 8080
            name: http
          resources:
            limits:
              cpu: '1'
              memory: 1024Mi
            requests:
              cpu: '1'
              memory: 1024Mi
        terminationGracePeriodSeconds: 2
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      provider: fabric8
      project: fabric8-tenant-che-migration-endpoints
      expose: 'true'
      version: ${VERSION}
      group: quickstart
    name: fabric8-tenant-che-migration-endpoints
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: fabric8-tenant-che-migration-endpoints
      provider: fabric8
      group: quickstart
parameters:
- description: Version
  name: VERSION
  value: latest
- description: The container image
  name: IMAGE
  value: "docker.io/dfestal/fabric8-tenant-che-migration:latest"
