apiVersion: v1
kind: Template
metadata:
  name: fabric8-tenant-che-migration-endpoints-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      provider: fabric8
      project: fabric8-tenant-che-migration-endpoints
      version: latest
      group: quickstart
    name: fabric8-tenant-che-migration-endpoints
  spec:
    replicas: 1
    selector:
      provider: fabric8
      project: fabric8-tenant-che-migration-endpoints
      group: quickstart
    template:
      metadata:
        labels:
          provider: fabric8
          project: fabric8-tenant-che-migration-endpoints
          version: ${VERSION}
          group: quickstart
      spec:
        containers:
        - env:
          - name: DEBUG
            value: ${DEBUG}
          - name: CLEANUP_SINGLE_TENANT
            value: ${CLEANUP_SINGLE_TENANT}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: ${IMAGE}
          imagePullPolicy: Always
          command: [ "java", "-jar", "io.fabric8.tenant.che.migration.rest.jar" ]
          name: fabric8-tenant-che-migration-endpoints
          ports:
          - containerPort: 8080
            name: http
          resources:
            limits:
              cpu: '1'
              memory: 1024Mi
            requests:
              cpu: '1'
              memory: 1024Mi
        terminationGracePeriodSeconds: 2
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      provider: fabric8
      project: fabric8-tenant-che-migration-endpoints
      version: ${VERSION}
      group: quickstart
    name: fabric8-tenant-che-migration-endpoints
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8081
    selector:
      project: fabric8-tenant-che-migration-endpoints
      provider: fabric8
      group: quickstart
parameters:
- description: Version
  name: VERSION
  value: latest
- description: The container image
  name: IMAGE
  value: "docker.io/dfestal/fabric8-tenant-che-migration:latest"
- description: If we should cleanup single resources after migration
  name: CLEANUP_SINGLE_TENANT
  value: "true"
- description: Add DEBUG logs
  name: DEBUG
  value: "false"

