apiVersion: v1
kind: Template
metadata:
  name: fabric8-tenant-che-migration-namespace-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: migration-${JOB_ID}
    annotations:
      request-id: ${REQUEST_ID}
    labels:
      migration:
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: migration-${JOB_ID}
        annotations:
          request-id: ${REQUEST_ID}
        labels:
          migration:
      spec:
        containers:
        - name: migration
          env:
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: java-options
                name: migration-settings
                optional: true
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                key: debug
                name: migration-settings
                optional: true
          - name: CLEANUP_SINGLE_TENANT
            valueFrom:
              configMapKeyRef:
                key: cleanup-single-tenant
                name: migration
                optional: true
          - name: CHE_MULTITENANT_SERVER
            valueFrom:
              configMapKeyRef:
                key: che-multitenant-server
                name: migration
                optional: true
          - name: CHE_DESTINATION_SERVER
            valueFrom:
              configMapKeyRef:
                key: che-destination-server
                name: migration
                optional: true
          - name: OSIO_TOKEN
            valueFrom:
              configMapKeyRef:
                key: osio-token
                name: migration
                optional: true
          - name: MIGRATION
            valueFrom:
              configMapKeyRef:
                key: migration
                name: migration
                optional: true
          - name: IDENTITY_ID
            valueFrom:
              configMapKeyRef:
                key: identity-id
                name: migration
                optional: true
          - name: REQUEST_ID
            valueFrom:
              configMapKeyRef:
                key: request-id
                name: migration
                optional: true
          - name: JOB_REQUEST_ID
            value: ${REQUEST_ID}
          image: ${IMAGE}
          imagePullPolicy: "Always"
        restartPolicy: Never
#        serviceAccount: che
parameters:
- description: The container image
  name: IMAGE
  value: "docker.io/dfestal/fabric8-tenant-che-migration:latest"
- description: Migration Job ID
  name: JOB_ID
  generate: expression
  from: "[a-z0-9]{12}"
- description: Request ID
  name: REQUEST_ID
  value: "theRequestId"
