apiVersion: v1
kind: Template
metadata:
  name: fabric8-tenant-che-migration-settings-configmap-template
objects:
- apiVersion: v1
  data:
    debug: ${DEBUG}
    java-options: ${JAVA_OPTIONS}
  kind: ConfigMap
  metadata:
    name: migration-settings
    namespace: dfestal-che
parameters:
- description: Add DEBUG logs
  name: DEBUG
  value: "false"
- description: The Java options to run the migration with
  name: JAVA_OPTIONS
  value: ""
