apiVersion: v1
kind: Template
metadata:
  name: che-tenant-maintainer-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: che-tenant-maintainer
    name: che-tenant-maintainer
  spec:
    replicas: 1
    selector:
      app: che-tenant-maintainer
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: che-tenant-maintainer
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: java-options
                name: che-tenant-maintainer
                optional: true
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                key: debug
                name: che-tenant-maintainer
                optional: true
          - name: COMMAND_TIMEOUT
            valueFrom:
              configMapKeyRef:
                key: command-timeout
                name: che-tenant-maintainer
                optional: true
          - name: JOLOKIA_READ_WRITE
            valueFrom:
              configMapKeyRef:
                key: jolokia-read-write
                name: che-tenant-maintainer
                optional: true
          - name: CHE_MULTITENANT_SERVER
            value: 'http://che-host:8080/wsmaster/api'
          - name: CHE_DESTINATION_SERVER
            value: 'http://rhche-host:8080/api'
          - name: OS_MASTER_URL
            value: 'http://f8osoproxy'
          - name: AB_JOLOKIA_AUTH_OPENSHIFT
            value: 'yes'
          - name: KEEP_ONLY_JSON_LOGS
            value: 'true'
          - name: SERVICE_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                key: service.account.id
                name: rhche
          - name: SERVICE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                key: service.account.secret
                name: rhche
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
          command: [ "./startRestEndpointsLocally.sh" ]
          name: che-tenant-maintainer
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8778
            name: jolokia
          resources:
            limits:
              memory: 1200Mi
            requests:
              memory: 512Mi
        terminationGracePeriodSeconds: 60
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: che-tenant-maintainer
    name: che-tenant-maintainer
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: che-tenant-maintainer
parameters:
- name: IMAGE
  value: "prod.registry.devshift.net/osio-prod/fabric8-services/fabric8-tenant-che-migration"
- name: IMAGE_TAG
  value: "latest"
- description: Add DEBUG logs
  name: DEBUG
  value: "false"
- description: The Java options to run the service with
  name: JAVA_OPTIONS
  value: ""
  
