apiVersion: v1
kind: Template
metadata:
  name: che-tenant-maintainer-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: che-tenant-maintainer
    name: che-tenant-maintainer
  spec:
    replicas: 1
    selector:
      app: che-tenant-maintainer
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: che-tenant-maintainer
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: java-options
                name: che-tenant-maintainer
                optional: true
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                key: debug
                name: che-tenant-maintainer
                optional: true
          - name: CHE_MULTITENANT_SERVER
            value: http://che-host:8080/wsmaster/api
          - name: CHE_DESTINATION_SERVER
            value: http://rhche-host:8080/api
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
          command: [ "java", "-jar", "io.fabric8.tenant.che.migration.rest.jar" ]
          name: che-tenant-maintainer
          ports:
          - containerPort: 8080
            name: http
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 512Mi
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: che-tenant-maintainer
    name: che-tenant-maintainer
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: che-tenant-maintainer
parameters:
- name: IMAGE
  value: "registry.devshift.net/fabric8-services/fabric8-tenant-che-migration"
- name: IMAGE_TAG
  value: "latest"
- description: Add DEBUG logs
  name: DEBUG
  value: "false"
- description: The Java options to run the service with
  name: JAVA_OPTIONS
  value: ""


